project:
  type: website

website:
  title: "nevermind"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NewGraphEnvironment/new_graphiti
format:
  html:
    theme: slate
    css: styles.css
execute:
  freeze: auto



