project:
  type: website

website:
  title: "nevermind"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NewGraphEnvironment?tab=repositories
format:
  html:
    theme:
    - vapor
    - custom.scss
    css: styles.css
execute:
  freeze: auto



